import { EventItem, UserSession, PurchasedTicket, SystemSettings, ReviewItem } from '@/types';

export const MOCK_USERS: UserSession[] = [
  {
    email: 'chioma@example.com',
    fullName: 'Chioma Adeyemi',
    role: 'Buyer',
    isVerifiedOrganizer: false,
    isSuspended: false,
  },
  {
    email: 'tunde@example.com',
    fullName: 'Tunde Okafor',
    role: 'Organizer',
    isVerifiedOrganizer: true,
    isSuspended: false,
  },
  {
    email: 'admin@babak.com',
    fullName: 'Admin User',
    role: 'Admin',
    isVerifiedOrganizer: false,
    isSuspended: false,
  },
  {
    email: 'zainab@example.com',
    fullName: 'Zainab Hassan',
    role: 'Buyer',
    isVerifiedOrganizer: false,
    isSuspended: false,
  },
  {
    email: 'nonso@example.com',
    fullName: 'Nonso Ejiofor',
    role: 'Organizer',
    isVerifiedOrganizer: true,
    isSuspended: false,
  },
];

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'evt-1717500000000',
    title: 'Lagos Afrobeats Festival 2026',
    description: 'Experience the ultimate celebration of African music and culture. Three days of live performances from top continental artists.',
    date: '2026-08-15',
    time: '18:00',
    venue: 'Eko Convention Centre, Victoria Island, Lagos',
    flyerUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=600&auto=format&fit=crop',
    ticketsConfig: [
      { name: 'General Access', price: 5000, capacity: 500, visibility: 'Public', soldCount: 145 },
      { name: 'VIP Suite', price: 15000, capacity: 100, visibility: 'Public', soldCount: 32 },
      { name: 'VVIP Lounge', price: 35000, capacity: 25, visibility: 'Invite Only', soldCount: 8 },
    ],
    adCustomizer: {
      backgroundType: 'gradient',
      backgroundValue: 'linear-gradient(135deg, #FFD700 0%, #FFA500 100%)',
      textColor: '#000',
      overlayText: 'Selling Fast',
      promote: true,
    },
    isPromoted: true,
    state: 'active',
    organizerEmail: 'tunde@example.com',
    category: 'Music',
  },
  {
    id: 'evt-1717510000000',
    title: 'Tech Summit West Africa',
    description: 'Connect with innovators and tech leaders. Keynote sessions, networking workshops, and startup pitches.',
    date: '2026-07-20',
    time: '09:00',
    venue: 'Landmark Centre, Lagos',
    flyerUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=600&auto=format&fit=crop',
    ticketsConfig: [
      { name: 'Attendee', price: 8000, capacity: 800, visibility: 'Public', soldCount: 342 },
      { name: 'Startup Exhibitor', price: 25000, capacity: 50, visibility: 'Public', soldCount: 18 },
    ],
    adCustomizer: {
      backgroundType: 'color',
      backgroundValue: '#1E40AF',
      textColor: '#fff',
      overlayText: 'Limited Slots',
      promote: false,
    },
    isPromoted: false,
    state: 'active',
    organizerEmail: 'nonso@example.com',
    category: 'Technology',
  },
  {
    id: 'evt-1717520000000',
    title: 'Nigerian Fashion Week 2026',
    description: 'Showcase of contemporary African fashion. Experience cutting-edge designs from emerging and established designers.',
    date: '2026-09-10',
    time: '14:00',
    venue: 'Oriental Hotel, Lagos',
    flyerUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=600&auto=format&fit=crop',
    ticketsConfig: [
      { name: 'Standard Entry', price: 3500, capacity: 600, visibility: 'Public', soldCount: 89 },
      { name: 'Front Row', price: 12000, capacity: 80, visibility: 'Public', soldCount: 22 },
    ],
    adCustomizer: {
      backgroundType: 'gradient',
      backgroundValue: 'linear-gradient(135deg, #EC4899 0%, #8B5CF6 100%)',
      textColor: '#fff',
      overlayText: 'Elite Event',
      promote: true,
    },
    isPromoted: true,
    state: 'active',
    organizerEmail: 'tunde@example.com',
    category: 'Fashion',
  },
  {
    id: 'evt-1717530000000',
    title: 'Golf Championship Pro Am',
    description: 'Premium golf tournament combining professional golfers with corporate sponsors. Networking gala dinner included.',
    date: '2026-07-28',
    time: '07:00',
    venue: 'Ikoyi Club 1938, Lagos',
    flyerUrl: 'https://images.unsplash.com/photo-1460066154156-71c40a1db086?q=80&w=600&auto=format&fit=crop',
    ticketsConfig: [
      { name: 'Spectator Pass', price: 2000, capacity: 300, visibility: 'Public', soldCount: 67 },
      { name: 'Golfer Entry', price: 50000, capacity: 72, visibility: 'Public', soldCount: 21 },
    ],
    adCustomizer: {
      backgroundType: 'color',
      backgroundValue: '#065F46',
      textColor: '#fff',
      overlayText: 'Premium',
      promote: false,
    },
    isPromoted: false,
    state: 'active',
    organizerEmail: 'nonso@example.com',
    category: 'Sports',
  },
  {
    id: 'evt-1717540000000',
    title: 'Wine & Culinary Arts Gala',
    description: 'An evening of exquisite wine pairings and fine dining. Curated by Michelin-trained chefs.',
    date: '2026-08-05',
    time: '19:30',
    venue: 'Four Seasons Hotel, Lagos',
    flyerUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=600&auto=format&fit=crop',
    ticketsConfig: [
      { name: 'Single Seat', price: 18000, capacity: 120, visibility: 'Public', soldCount: 43 },
      { name: 'Table of 6', price: 95000, capacity: 20, visibility: 'Public', soldCount: 5 },
    ],
    adCustomizer: {
      backgroundType: 'gradient',
      backgroundValue: 'linear-gradient(135deg, #7C3AED 0%, #DC2626 100%)',
      textColor: '#fff',
      overlayText: 'Exclusive',
      promote: true,
    },
    isPromoted: true,
    state: 'active',
    organizerEmail: 'tunde@example.com',
    category: 'Lifestyle',
  },
  {
    id: 'evt-1717550000000',
    title: 'The Olowojare\'s Wedding 2026',
    description: 'A celebration of love and tradition. Join us for a memorable day filled with joy, food, and festivities.',
    date: '2026-07-15',
    time: '16:00',
    venue: 'Lekki Conservation Centre, Lagos',
    flyerUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=600&auto=format&fit=crop',
    ticketsConfig: [
      { name: 'Guest Reservation', price: 0, capacity: 500, visibility: 'Public', soldCount: 87 },
    ],
    adCustomizer: {
      backgroundType: 'gradient',
      backgroundValue: 'linear-gradient(135deg, #F472B6 0%, #FBBF24 100%)',
      textColor: '#fff',
      overlayText: 'Celebration',
      promote: false,
    },
    isPromoted: false,
    state: 'active',
    organizerEmail: 'tunde@example.com',
    category: 'Wedding',
  },
  {
    id: 'evt-1717555000000',
    title: 'ILORIN AUTOMOTIVE FESTIVAL - CAR SHOW 2026',
    description: 'Experience the ultimate celebration of automobiles! Premium car showcase featuring exotic vehicles, luxury brands, custom builds, and interactive automotive experiences. Network with car enthusiasts and dealers.',
    date: '2026-07-18',
    time: '09:00',
    venue: 'Ilorin International Exhibition Centre, Kwara State',
    flyerUrl: 'https://images.unsplash.com/photo-1552820728-8ac41f1ce891?q=80&w=600&auto=format&fit=crop',
    ticketsConfig: [
      { name: 'General Admission', price: 3500, capacity: 1000, visibility: 'Public', soldCount: 423 },
      { name: 'VIP Showcase Pass', price: 12000, capacity: 200, visibility: 'Public', soldCount: 89 },
      { name: 'Premium Dealer Access', price: 25000, capacity: 50, visibility: 'Invite Only', soldCount: 31 },
    ],
    adCustomizer: {
      backgroundType: 'gradient',
      backgroundValue: 'linear-gradient(135deg, #DC2626 0%, #1F2937 100%)',
      textColor: '#fff',
      overlayText: 'Rev Your Engine',
      promote: true,
    },
    isPromoted: true,
    state: 'active',
    organizerEmail: 'nonso@example.com',
    category: 'Sports',
  },
  {
    id: 'evt-1717565000000',
    title: 'PSG vs ARSENAL - CHAMPIONS LEAGUE FINAL CINEMA VIEWING',
    description: 'Experience the ultimate football showdown! Watch PSG face Arsenal in the Champions League Final on the big screen with fellow passionate fans. Premium sound system, comfortable seating, and live commentary.',
    date: '2026-06-20',
    time: '19:00',
    venue: 'Cineplex Premium Cinema, Ikoyi, Lagos',
    flyerUrl: 'https://images.unsplash.com/photo-1552672597-70245560323e?q=80&w=600&auto=format&fit=crop',
    ticketsConfig: [
      { name: 'Standard Seat', price: 2500, capacity: 400, visibility: 'Public', soldCount: 267 },
      { name: 'VIP Comfort', price: 6500, capacity: 100, visibility: 'Public', soldCount: 72 },
      { name: 'Premium Box Seat', price: 15000, capacity: 30, visibility: 'Public', soldCount: 18 },
    ],
    adCustomizer: {
      backgroundType: 'color',
      backgroundValue: '#1E40AF',
      textColor: '#fff',
      overlayText: 'The Beautiful Game',
      promote: true,
    },
    isPromoted: true,
    state: 'active',
    organizerEmail: 'tunde@example.com',
    category: 'Sports',
  },
  {
    id: 'evt-1717560000000',
    title: 'Stand-Up Comedy Night Ibo Nights',
    description: 'Hilarious comedy performances from top Nigerian comedians. Laugh, drink, and network with friends in an intimate setting.',
    date: '2026-07-22',
    time: '20:00',
    venue: 'The Dome, Ikoyi, Lagos',
    flyerUrl: 'https://images.unsplash.com/photo-1503042598615-2e08da941bba?q=80&w=600&auto=format&fit=crop',
    ticketsConfig: [
      { name: 'General Admission', price: 2500, capacity: 400, visibility: 'Public', soldCount: 156 },
      { name: 'VIP Table', price: 12000, capacity: 50, visibility: 'Public', soldCount: 28 },
      { name: 'Couple\'s Lounge', price: 8000, capacity: 80, visibility: 'Public', soldCount: 34 },
    ],
    adCustomizer: {
      backgroundType: 'color',
      backgroundValue: '#7C3AED',
      textColor: '#fff',
      overlayText: 'Laugh Out Loud',
      promote: false,
    },
    isPromoted: false,
    state: 'active',
    organizerEmail: 'nonso@example.com',
    category: 'Comedy',
  },
  {
    id: 'evt-1717570000000',
    title: 'Annual Charity Basketball Tournament',
    description: 'Tournament featuring corporate teams competing for glory. Proceeds go to underprivileged youth sports programs.',
    date: '2026-08-22',
    time: '10:00',
    venue: 'Lagos State Sports Complex, Surulere',
    flyerUrl: 'https://images.unsplash.com/photo-1546519638-68ecc39aab07?q=80&w=600&auto=format&fit=crop',
    ticketsConfig: [
      { name: 'Match Ticket', price: 1500, capacity: 800, visibility: 'Public', soldCount: 234 },
      { name: 'VIP Courtside', price: 8000, capacity: 100, visibility: 'Public', soldCount: 45 },
      { name: 'Tournament Pass (Full Day)', price: 5000, capacity: 600, visibility: 'Public', soldCount: 298 },
    ],
    adCustomizer: {
      backgroundType: 'gradient',
      backgroundValue: 'linear-gradient(135deg, #DC2626 0%, #1F2937 100%)',
      textColor: '#fff',
      overlayText: 'For a Cause',
      promote: true,
    },
    isPromoted: true,
    state: 'active',
    organizerEmail: 'nonso@example.com',
    category: 'Sports',
  },
  {
    id: 'evt-1717580000000',
    title: 'Wellness & Yoga Retreat Weekend',
    description: 'Three-day immersive wellness experience with yoga, meditation, holistic healing, and organic farm-to-table meals.',
    date: '2026-09-03',
    time: '08:00',
    venue: 'Abeokuta Wellness Center, Ogun State',
    flyerUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=600&auto=format&fit=crop',
    ticketsConfig: [
      { name: 'Single Attendee', price: 15000, capacity: 150, visibility: 'Public', soldCount: 89 },
      { name: 'Couple Package', price: 26000, capacity: 50, visibility: 'Public', soldCount: 18 },
      { name: 'Premium Suite', price: 45000, capacity: 20, visibility: 'Invite Only', soldCount: 6 },
    ],
    adCustomizer: {
      backgroundType: 'gradient',
      backgroundValue: 'linear-gradient(135deg, #10B981 0%, #6366F1 100%)',
      textColor: '#fff',
      overlayText: 'Find Your Peace',
      promote: false,
    },
    isPromoted: false,
    state: 'active',
    organizerEmail: 'tunde@example.com',
    category: 'Lifestyle',
  },
  {
    id: 'evt-1717590000000',
    title: 'Digital Marketing Workshop Series',
    description: 'Intensive 5-day workshop covering SEO, social media, content marketing, and analytics. Hands-on training with industry experts.',
    date: '2026-08-11',
    time: '10:00',
    venue: 'Tech Hub Lagos, Ikoyi',
    flyerUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=600&auto=format&fit=crop',
    ticketsConfig: [
      { name: 'Early Bird', price: 12000, capacity: 200, visibility: 'Public', soldCount: 178 },
      { name: 'Professional Pass', price: 20000, capacity: 100, visibility: 'Public', soldCount: 67 },
      { name: 'Corporate Sponsorship', price: 50000, capacity: 20, visibility: 'Public', soldCount: 8 },
    ],
    adCustomizer: {
      backgroundType: 'color',
      backgroundValue: '#0284C7',
      textColor: '#fff',
      overlayText: 'Skills Upgrade',
      promote: false,
    },
    isPromoted: false,
    state: 'active',
    organizerEmail: 'nonso@example.com',
    category: 'Technology',
  },
  {
    id: 'evt-1717600000000',
    title: 'Art Exhibition: \"Lagos Through Colors\"',
    description: 'Contemporary art exhibition showcasing local and international artists. Interactive installations and live painting demonstrations.',
    date: '2026-08-30',
    time: '15:00',
    venue: 'MUSON Centre, Victoria Island',
    flyerUrl: 'https://images.unsplash.com/photo-1578926314433-96b2d9a91f55?q=80&w=600&auto=format&fit=crop',
    ticketsConfig: [
      { name: 'General Admission', price: 3000, capacity: 500, visibility: 'Public', soldCount: 156 },
      { name: 'Guided Tour', price: 6000, capacity: 100, visibility: 'Public', soldCount: 34 },
      { name: 'VIP Artist Meet & Greet', price: 15000, capacity: 30, visibility: 'Public', soldCount: 12 },
    ],
    adCustomizer: {
      backgroundType: 'gradient',
      backgroundValue: 'linear-gradient(135deg, #8B5CF6 0%, #EC4899 100%)',
      textColor: '#fff',
      overlayText: 'See the Art',
      promote: true,
    },
    isPromoted: true,
    state: 'active',
    organizerEmail: 'tunde@example.com',
    category: 'Exhibition',
  },
  {
    id: 'evt-1717610000000',
    title: 'Networking Breakfast for Female Entrepreneurs',
    description: 'Exclusive breakfast event connecting female business owners, investors, and mentors. Panel discussions on funding, scaling, and leadership.',
    date: '2026-07-30',
    time: '07:30',
    venue: 'Radisson Blu Lagos, Ikeja',
    flyerUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=600&auto=format&fit=crop',
    ticketsConfig: [
      { name: 'Attendee', price: 5000, capacity: 300, visibility: 'Public', soldCount: 189 },
      { name: 'Speaker/Mentor Pass', price: 8000, capacity: 50, visibility: 'Invite Only', soldCount: 28 },
    ],
    adCustomizer: {
      backgroundType: 'color',
      backgroundValue: '#EC4899',
      textColor: '#fff',
      overlayText: 'Empowering Women',
      promote: false,
    },
    isPromoted: false,
    state: 'active',
    organizerEmail: 'nonso@example.com',
    category: 'Networking',
  },
  {
    id: 'evt-1717620000000',
    title: 'ZADDY\'S CREAMERY',
    description: 'Premium ice cream experience showcase. Taste artisanal ice cream flavors and learn about our unique creamery business model. Free demo to experience ZADDY\'S quality - normally ₦2,000 for a small scope.',
    date: '2026-07-25',
    time: '11:00',
    venue: 'Lekki Phase 1, Lagos',
    flyerUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?q=80&w=600&auto=format&fit=crop',
    ticketsConfig: [
      { name: 'Small Scope Demo (FREE)', price: 0, capacity: 300, visibility: 'Public', soldCount: 124 },
      { name: 'Premium Tasting Bundle', price: 2000, capacity: 150, visibility: 'Public', soldCount: 56 },
    ],
    adCustomizer: {
      backgroundType: 'gradient',
      backgroundValue: 'linear-gradient(135deg, #F97316 0%, #FBBF24 100%)',
      textColor: '#fff',
      overlayText: 'Taste the Vibe',
      promote: true,
    },
    isPromoted: true,
    state: 'active',
    organizerEmail: 'tunde@example.com',
    category: 'Lifestyle',
  },
];

export const INITIAL_TICKETS: PurchasedTicket[] = [
  {
    id: 'tkt-1717500000000-0',
    eventId: 'evt-1717500000000',
    ticketTierName: 'General Access',
    buyerName: 'Chioma Adeyemi',
    buyerEmail: 'chioma@example.com',
    qrCode: 'BABAK_TKT_1717500_NBK-567821-42',
    purchaseDate: '2026-06-01',
    pricePaid: 5000,
    feePaid: 250,
    serialNumber: 'NBK-567821-42',
    isReselling: false,
    paymentGateway: 'paystack',
    isValidated: false,
  },
  {
    id: 'tkt-1717500000001-0',
    eventId: 'evt-1717510000000',
    ticketTierName: 'Attendee',
    buyerName: 'Zainab Hassan',
    buyerEmail: 'zainab@example.com',
    qrCode: 'BABAK_TKT_1717510_NBK-234567-89',
    purchaseDate: '2026-06-02',
    pricePaid: 8000,
    feePaid: 250,
    serialNumber: 'NBK-234567-89',
    isReselling: true,
    resalePrice: 9500,
    paymentGateway: 'opay',
    isValidated: false,
  },
  {
    id: 'tkt-1717550000000-0',
    eventId: 'evt-1717550000000',
    ticketTierName: 'Guest Reservation',
    buyerName: 'Chioma Adeyemi',
    buyerEmail: 'chioma@example.com',
    qrCode: 'BABAK_TKT_1717550_WED-001234-99',
    purchaseDate: '2026-06-10',
    pricePaid: 0,
    feePaid: 0,
    serialNumber: 'WED-001234-99',
    isReselling: false,
    paymentGateway: 'free',
    isValidated: false,
  },
  {
    id: 'tkt-1717555000000-0',
    eventId: 'evt-1717555000000',
    ticketTierName: 'General Admission',
    buyerName: 'Tunde Okafor',
    buyerEmail: 'tunde@example.com',
    qrCode: 'BABAK_TKT_1717555_CAR-345678-11',
    purchaseDate: '2026-06-08',
    pricePaid: 3500,
    feePaid: 250,
    serialNumber: 'CAR-345678-11',
    isReselling: false,
    paymentGateway: 'paystack',
    isValidated: false,
  },
  {
    id: 'tkt-1717555000001-0',
    eventId: 'evt-1717555000000',
    ticketTierName: 'VIP Showcase Pass',
    buyerName: 'Nonso Ejiofor',
    buyerEmail: 'nonso@example.com',
    qrCode: 'BABAK_TKT_1717555_CAR-876543-22',
    purchaseDate: '2026-06-07',
    pricePaid: 12000,
    feePaid: 250,
    serialNumber: 'CAR-876543-22',
    isReselling: false,
    paymentGateway: 'opay',
    isValidated: false,
  },
  {
    id: 'tkt-1717565000000-0',
    eventId: 'evt-1717565000000',
    ticketTierName: 'Standard Seat',
    buyerName: 'Chioma Adeyemi',
    buyerEmail: 'chioma@example.com',
    qrCode: 'BABAK_TKT_1717565_PSG-567890-33',
    purchaseDate: '2026-06-12',
    pricePaid: 2500,
    feePaid: 250,
    serialNumber: 'PSG-567890-33',
    isReselling: true,
    resalePrice: 3500,
    paymentGateway: 'paystack',
    isValidated: false,
  },
  {
    id: 'tkt-1717565000001-0',
    eventId: 'evt-1717565000000',
    ticketTierName: 'VIP Comfort',
    buyerName: 'Zainab Hassan',
    buyerEmail: 'zainab@example.com',
    qrCode: 'BABAK_TKT_1717565_PSG-112233-44',
    purchaseDate: '2026-06-11',
    pricePaid: 6500,
    feePaid: 250,
    serialNumber: 'PSG-112233-44',
    isReselling: false,
    paymentGateway: 'paystack',
    isValidated: false,
  },
  {
    id: 'tkt-1717560000000-0',
    eventId: 'evt-1717560000000',
    ticketTierName: 'VIP Table',
    buyerName: 'Nonso Ejiofor',
    buyerEmail: 'nonso@example.com',
    qrCode: 'BABAK_TKT_1717560_COM-567234-01',
    purchaseDate: '2026-06-05',
    pricePaid: 12000,
    feePaid: 250,
    serialNumber: 'COM-567234-01',
    isReselling: false,
    paymentGateway: 'paystack',
    isValidated: false,
  },
  {
    id: 'tkt-1717570000000-0',
    eventId: 'evt-1717570000000',
    ticketTierName: 'Tournament Pass (Full Day)',
    buyerName: 'Tunde Okafor',
    buyerEmail: 'tunde@example.com',
    qrCode: 'BABAK_TKT_1717570_BAS-890123-55',
    purchaseDate: '2026-06-08',
    pricePaid: 5000,
    feePaid: 250,
    serialNumber: 'BAS-890123-55',
    isReselling: true,
    resalePrice: 6000,
    paymentGateway: 'paystack',
    isValidated: false,
  },
  {
    id: 'tkt-1717580000000-0',
    eventId: 'evt-1717580000000',
    ticketTierName: 'Couple Package',
    buyerName: 'Zainab Hassan',
    buyerEmail: 'zainab@example.com',
    qrCode: 'BABAK_TKT_1717580_WLL-456789-12',
    purchaseDate: '2026-06-03',
    pricePaid: 26000,
    feePaid: 250,
    serialNumber: 'WLL-456789-12',
    isReselling: false,
    paymentGateway: 'opay',
    isValidated: false,
  },
  {
    id: 'tkt-1717590000000-0',
    eventId: 'evt-1717590000000',
    ticketTierName: 'Professional Pass',
    buyerName: 'Chioma Adeyemi',
    buyerEmail: 'chioma@example.com',
    qrCode: 'BABAK_TKT_1717590_MKT-234567-45',
    purchaseDate: '2026-06-09',
    pricePaid: 20000,
    feePaid: 250,
    serialNumber: 'MKT-234567-45',
    isReselling: false,
    paymentGateway: 'paystack',
    isValidated: false,
  },
  {
    id: 'tkt-1717600000000-0',
    eventId: 'evt-1717600000000',
    ticketTierName: 'VIP Artist Meet & Greet',
    buyerName: 'Nonso Ejiofor',
    buyerEmail: 'nonso@example.com',
    qrCode: 'BABAK_TKT_1717600_ART-789012-34',
    purchaseDate: '2026-06-06',
    pricePaid: 15000,
    feePaid: 250,
    serialNumber: 'ART-789012-34',
    isReselling: false,
    paymentGateway: 'opay',
    isValidated: false,
  },
  {
    id: 'tkt-1717620000000-0',
    eventId: 'evt-1717620000000',
    ticketTierName: 'Small Scope Demo (FREE)',
    buyerName: 'Chioma Adeyemi',
    buyerEmail: 'chioma@example.com',
    qrCode: 'BABAK_TKT_1717620_ICE-123456-78',
    purchaseDate: '2026-06-10',
    pricePaid: 0,
    feePaid: 0,
    serialNumber: 'ICE-123456-78',
    isReselling: false,
    paymentGateway: 'free',
    isValidated: false,
  },
  {
    id: 'tkt-1717620000001-0',
    eventId: 'evt-1717620000000',
    ticketTierName: 'Premium Tasting Bundle',
    buyerName: 'Zainab Hassan',
    buyerEmail: 'zainab@example.com',
    qrCode: 'BABAK_TKT_1717620_ICE-654321-90',
    purchaseDate: '2026-06-11',
    pricePaid: 2000,
    feePaid: 250,
    serialNumber: 'ICE-654321-90',
    isReselling: false,
    paymentGateway: 'paystack',
    isValidated: false,
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  flatFee: 250,
  promotionPrice: 5000,
  supportedGateways: {
    paystack: true,
    opay: true,
    alatpay: false,
  },
};

export const INITIAL_REVIEWS: ReviewItem[] = [
  {
    id: 'rev-1',
    eventId: 'evt-1717500000000',
    userEmail: 'chioma@example.com',
    userName: 'Chioma Adeyemi',
    rating: 5,
    comment: 'Amazing event! The organization was top-notch and the performances were incredible.',
    timestamp: '2026-06-03',
  },
  {
    id: 'rev-2',
    eventId: 'evt-1717510000000',
    userEmail: 'zainab@example.com',
    userName: 'Zainab Hassan',
    rating: 4,
    comment: 'Great lineup of speakers. Networking session could have been longer.',
    timestamp: '2026-06-02',
  },
  {
    id: 'rev-3',
    eventId: 'evt-1717550000000',
    userEmail: 'chioma@example.com',
    userName: 'Chioma Adeyemi',
    rating: 4,
    comment: 'Wonderful family celebration with beautiful ambiance and great hospitality.',
    timestamp: '2026-06-11',
  },
  {
    id: 'rev-4',
    eventId: 'evt-1717555000000',
    userEmail: 'tunde@example.com',
    userName: 'Tunde Okafor',
    rating: 5,
    comment: 'Ilorin Automotive Festival was incredible! Saw so many exotic cars and met amazing car enthusiasts. Definitely coming back next year!',
    timestamp: '2026-06-12',
  },
  {
    id: 'rev-5',
    eventId: 'evt-1717565000000',
    userEmail: 'chioma@example.com',
    userName: 'Chioma Adeyemi',
    rating: 5,
    comment: 'Watching the PSG vs Arsenal match on the big screen was epic! Great atmosphere and excellent cinema quality.',
    timestamp: '2026-06-13',
  },
  {
    id: 'rev-6',
    eventId: 'evt-1717600000000',
    userEmail: 'nonso@example.com',
    userName: 'Nonso Ejiofor',
    rating: 5,
    comment: 'Lagos Through Colors art exhibition was phenomenal. The artists are truly talented.',
    timestamp: '2026-06-10',
  },
  {
    id: 'rev-7',
    eventId: 'evt-1717620000000',
    userEmail: 'chioma@example.com',
    userName: 'Chioma Adeyemi',
    rating: 5,
    comment: 'ZADDY\'S CREAMERY is absolutely delicious! Free demo was the perfect way to discover this gem. Already planning to come back with friends!',
    timestamp: '2026-06-11',
  },
];

export const CATEGORIES = [
  'Music',
  'Technology',
  'Fashion',
  'Sports',
  'Lifestyle',
  'Comedy',
  'Wedding',
  'Conference',
  'Workshop',
  'Exhibition',
  'Networking',
];
