import { EventItem, UserSession, PurchasedTicket, SystemSettings, ReviewItem } from '@/types';

export const MOCK_USERS: UserSession[] = [
  {
    email: 'chioma@example.com',
    fullName: 'Chioma Adeyemi',
    role: 'Buyer',
    isVerifiedOrganizer: false,
    isSuspended: false,
  },
  {
    email: 'tunde@example.com',
    fullName: 'Tunde Okafor',
    role: 'Organizer',
    isVerifiedOrganizer: true,
    isSuspended: false,
  },
  {
    email: 'admin@babak.com',
    fullName: 'Admin User',
    role: 'Admin',
    isVerifiedOrganizer: false,
    isSuspended: false,
  },
  {
    email: 'zainab@example.com',
    fullName: 'Zainab Hassan',
    role: 'Buyer',
    isVerifiedOrganizer: false,
    isSuspended: false,
  },
  {
    email: 'nonso@example.com',
    fullName: 'Nonso Ejiofor',
    role: 'Organizer',
    isVerifiedOrganizer: true,
    isSuspended: false,
  },
];

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'evt-1717500000000',
    title: 'Lagos Afrobeats Festival 2026',
    description: 'Experience the ultimate celebration of African music and culture. Three days of live performances from top continental artists.',
    date: '2026-08-15',
    time: '18:00',
    venue: 'Eko Convention Centre, Victoria Island, Lagos',
    flyerUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=600&auto=format&fit=crop',
    ticketsConfig: [
      { name: 'General Access', price: 5000, capacity: 500, visibility: 'Public', soldCount: 145 },
      { name: 'VIP Suite', price: 15000, capacity: 100, visibility: 'Public', soldCount: 32 },
      { name: 'VVIP Lounge', price: 35000, capacity: 25, visibility: 'Invite Only', soldCount: 8 },
    ],
    adCustomizer: {
      backgroundType: 'gradient',
      backgroundValue: 'linear-gradient(135deg, #FFD700 0%, #FFA500 100%)',
      textColor: '#000',
      overlayText: 'Selling Fast',
      promote: true,
    },
    isPromoted: true,
    state: 'active',
    organizerEmail: 'tunde@example.com',
    category: 'Music',
  },
  {
    id: 'evt-1717510000000',
    title: 'Tech Summit West Africa',
    description: 'Connect with innovators and tech leaders. Keynote sessions, networking workshops, and startup pitches.',
    date: '2026-07-20',
    time: '09:00',
    venue: 'Landmark Centre, Lagos',
    flyerUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=600&auto=format&fit=crop',
    ticketsConfig: [
      { name: 'Attendee', price: 8000, capacity: 800, visibility: 'Public', soldCount: 342 },
      { name: 'Startup Exhibitor', price: 25000, capacity: 50, visibility: 'Public', soldCount: 18 },
    ],
    adCustomizer: {
      backgroundType: 'color',
      backgroundValue: '#1E40AF',
      textColor: '#fff',
      overlayText: 'Limited Slots',
      promote: false,
    },
    isPromoted: false,
    state: 'active',
    organizerEmail: 'nonso@example.com',
    category: 'Technology',
  },
  {
    id: 'evt-1717520000000',
    title: 'Nigerian Fashion Week 2026',
    description: 'Showcase of contemporary African fashion. Experience cutting-edge designs from emerging and established designers.',
    date: '2026-09-10',
    time: '14:00',
    venue: 'Oriental Hotel, Lagos',
    flyerUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=600&auto=format&fit=crop',
    ticketsConfig: [
      { name: 'Standard Entry', price: 3500, capacity: 600, visibility: 'Public', soldCount: 89 },
      { name: 'Front Row', price: 12000, capacity: 80, visibility: 'Public', soldCount: 22 },
    ],
    adCustomizer: {
      backgroundType: 'gradient',
      backgroundValue: 'linear-gradient(135deg, #EC4899 0%, #8B5CF6 100%)',
      textColor: '#fff',
      overlayText: 'Elite Event',
      promote: true,
    },
    isPromoted: true,
    state: 'active',
    organizerEmail: 'tunde@example.com',
    category: 'Fashion',
  },
  {
    id: 'evt-1717530000000',
    title: 'Golf Championship Pro Am',
    description: 'Premium golf tournament combining professional golfers with corporate sponsors. Networking gala dinner included.',
    date: '2026-07-28',
    time: '07:00',
    venue: 'Ikoyi Club 1938, Lagos',
    flyerUrl: 'https://images.unsplash.com/photo-1460066154156-71c40a1db086?q=80&w=600&auto=format&fit=crop',
    ticketsConfig: [
      { name: 'Spectator Pass', price: 2000, capacity: 300, visibility: 'Public', soldCount: 67 },
      { name: 'Golfer Entry', price: 50000, capacity: 72, visibility: 'Public', soldCount: 21 },
    ],
    adCustomizer: {
      backgroundType: 'color',
      backgroundValue: '#065F46',
      textColor: '#fff',
      overlayText: 'Premium',
      promote: false,
    },
    isPromoted: false,
    state: 'active',
    organizerEmail: 'nonso@example.com',
    category: 'Sports',
  },
  {
    id: 'evt-1717540000000',
    title: 'Wine & Culinary Arts Gala',
    description: 'An evening of exquisite wine pairings and fine dining. Curated by Michelin-trained chefs.',
    date: '2026-08-05',
    time: '19:30',
    venue: 'Four Seasons Hotel, Lagos',
    flyerUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=600&auto=format&fit=crop',
    ticketsConfig: [
      { name: 'Single Seat', price: 18000, capacity: 120, visibility: 'Public', soldCount: 43 },
      { name: 'Table of 6', price: 95000, capacity: 20, visibility: 'Public', soldCount: 5 },
    ],
    adCustomizer: {
      backgroundType: 'gradient',
      backgroundValue: 'linear-gradient(135deg, #7C3AED 0%, #DC2626 100%)',
      textColor: '#fff',
      overlayText: 'Exclusive',
      promote: true,
    },
    isPromoted: true,
    state: 'active',
    organizerEmail: 'tunde@example.com',
    category: 'Lifestyle',
  },
];

export const INITIAL_TICKETS: PurchasedTicket[] = [
  {
    id: 'tkt-1717500000000-0',
    eventId: 'evt-1717500000000',
    ticketTierName: 'General Access',
    buyerName: 'Chioma Adeyemi',
    buyerEmail: 'chioma@example.com',
    qrCode: 'BABAK_TKT_1717500_NBK-567821-42',
    purchaseDate: '2026-06-01',
    pricePaid: 5000,
    feePaid: 250,
    serialNumber: 'NBK-567821-42',
    isReselling: false,
    paymentGateway: 'paystack',
    isValidated: false,
  },
  {
    id: 'tkt-1717500000001-0',
    eventId: 'evt-1717510000000',
    ticketTierName: 'Attendee',
    buyerName: 'Zainab Hassan',
    buyerEmail: 'zainab@example.com',
    qrCode: 'BABAK_TKT_1717510_NBK-234567-89',
    purchaseDate: '2026-06-02',
    pricePaid: 8000,
    feePaid: 250,
    serialNumber: 'NBK-234567-89',
    isReselling: true,
    resalePrice: 9500,
    paymentGateway: 'opay',
    isValidated: false,
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  flatFee: 250,
  promotionPrice: 5000,
  supportedGateways: {
    paystack: true,
    opay: true,
    alatpay: false,
  },
};

export const INITIAL_REVIEWS: ReviewItem[] = [
  {
    id: 'rev-1',
    eventId: 'evt-1717500000000',
    userEmail: 'chioma@example.com',
    userName: 'Chioma Adeyemi',
    rating: 5,
    comment: 'Amazing event! The organization was top-notch and the performances were incredible.',
    timestamp: '2026-06-03',
  },
  {
    id: 'rev-2',
    eventId: 'evt-1717510000000',
    userEmail: 'zainab@example.com',
    userName: 'Zainab Hassan',
    rating: 4,
    comment: 'Great lineup of speakers. Networking session could have been longer.',
    timestamp: '2026-06-02',
  },
];

export const CATEGORIES = [
  'Music',
  'Technology',
  'Fashion',
  'Sports',
  'Lifestyle',
  'Comedy',
  'Conference',
  'Workshop',
  'Exhibition',
  'Networking',
];
